using DtHub.Core.Localization;

namespace DtHub.Core.Papycha;

/// <summary>
/// What the introduction block of a quest page announces.
///
/// These facts are generated by a built-in block of the site, not
/// written by hand: their markup is therefore regular from one
/// quest to another, unlike the body of the article. This is what
/// makes them parseable without guessing.
/// </summary>
public sealed record QuestFacts
{
    /// <summary>Achievement the quest belongs to, when it has one.</summary>
    public string? Success { get; init; }

    /// <summary>
    /// What the chain rewards at the end, for example a Dofus.
    /// </summary>
    public string? Finality { get; init; }

    /// <summary>
    /// Announced type: Principale, Alignement Bonta, Événementielle...
    /// </summary>
    public string? Type { get; init; }

    /// <summary>
    /// Rank of the quest within its achievement, starting from one.
    /// </summary>
    public int StepNumber { get; init; }

    /// <summary>Number of quests in the achievement.</summary>
    public int StepCount { get; init; }

    /// <summary>How the quest starts, in one sentence.</summary>
    public string? Start { get; init; }

    /// <summary>True if the quest is part of a known chain.</summary>
    public bool HasChain => StepCount > 1 && StepNumber > 0;

    /// <summary>
    /// "Step 3/4", or an empty string when not part of a chain.
    /// </summary>
    public string StepText => HasChain ? Strings.Format("StepShort", StepNumber, StepCount) : string.Empty;
}
