using System.Text.RegularExpressions;

namespace DtHub.Tests.App;

/// <summary>
/// Checks that every button in the interface is wired to a command
/// that really exists.
///
/// WPF reports nothing when a command cannot be found: the button
/// stays clickable and does nothing. Three buttons on the Devices tab
/// stayed dead for this reason, without the slightest message. The
/// check is done on the text of the files, otherwise it would require
/// referencing the UI project and moving the whole test suite over to
/// Windows.
/// </summary>
public sealed class CommandBindingTests
{
    private static readonly Regex BoundCommand = new(
        """Command\s*=\s*"\{Binding\s+(?<path>[^,}]+)""",
        RegexOptions.Singleline);

    [Fact]
    public void Chaque_commande_liee_dans_le_XAML_existe_dans_un_view_model()
    {
        var app = Path.Combine(RepositoryRoot(), "src", "DtHub.App");
        var sources = string.Concat(Directory
            .EnumerateFiles(app, "*.cs", SearchOption.AllDirectories)
            .Select(File.ReadAllText));

        List<string> missing = [];

        foreach (var view in Directory.EnumerateFiles(app, "*.xaml", SearchOption.AllDirectories))
        {
            foreach (Match match in BoundCommand.Matches(File.ReadAllText(view)))
            {
                // "DataContext.RestartCommand" or "RestartCommand":
                // only the last segment names the command.
                var name = match.Groups["path"].Value.Trim().Split('.')[^1].Trim();

                if (!name.EndsWith("Command", StringComparison.Ordinal) || Declares(sources, name))
                {
                    continue;
                }

                missing.Add($"{Path.GetFileName(view)} : {name}");
            }
        }

        Assert.Empty(missing);
    }

    /// <summary>
    /// True if the command is declared by hand, or generated by
    /// <c>[RelayCommand]</c> from a method of the same name, with or
    /// without the <c>Async</c> suffix that the generator strips.
    /// </summary>
    private static bool Declares(string sources, string name)
    {
        var method = name[..^"Command".Length];

        return sources.Contains(name, StringComparison.Ordinal)
            || Regex.IsMatch(
                sources,
                $@"\[RelayCommand[^\]]*\][\s\S]{{0,400}}?\b{Regex.Escape(method)}(Async)?\s*\(");
    }

    private static string RepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);

        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "DtHub.slnx")))
        {
            directory = directory.Parent;
        }

        Assert.NotNull(directory);

        return directory.FullName;
    }
}
